version: "3.7"

services:

  postgres-rps:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - contract_testing

  broker-rps:
    image: pactfoundation/pact-broker
    links:
      - postgres-rps
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_rps
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_rps
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres-rps
      PACT_BROKER_DATABASE_NAME: postgres
    depends_on:
      - postgres-rps
    networks:
      - contract_testing

networks:
  contract_testing: