version: "3.7"

services:

  redis-rps:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./src/main/resources/redis/:/scripts"

  rps-service:
    container_name: rps-service
    image: rps-service-img
    environment:
        - REDIS_HOST=redis-rps
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-rps
    ports:
      - 8080:8080
    restart: always